# Generated by Django 6.0.7 on 2026-09-11 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/', verbose_name='Profil fotoğrafı'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='Hakkında'),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Doğum tarihi'),
        ),
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, max_length=60, verbose_name='Görünen ad'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ev, İş...', max_length=30, verbose_name='Başlık')),
                ('city', models.CharField(max_length=50, verbose_name='İl')),
                ('district', models.CharField(max_length=50, verbose_name='İlçe')),
                ('full_address', models.TextField(verbose_name='Açık adres')),
                ('is_default', models.BooleanField(default=False, verbose_name='Varsayılan adres')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Adres',
                'verbose_name_plural': 'Adresler',
                'ordering': ['-is_default', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProfileSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books_public', models.BooleanField(default=False, verbose_name='Kitaplarım herkese açık')),
                ('show_email', models.BooleanField(default=False, verbose_name='E-postamı göster')),
                ('theme', models.CharField(choices=[('light', 'Açık'), ('dark', 'Koyu')], default='light', max_length=10, verbose_name='Tema')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='E-posta bildirimleri')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Profil ayarı',
                'verbose_name_plural': 'Profil ayarları',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('x', 'X'), ('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('website', 'Web sitesi')], max_length=20, verbose_name='Platform')),
                ('url', models.URLField(verbose_name='Adres')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Sosyal bağlantı',
                'verbose_name_plural': 'Sosyal bağlantılar',
                'constraints': [models.UniqueConstraint(fields=('profile', 'platform'), name='uniq_profile_platform')],
            },
        ),
    ]
